vich_uploader:
    db_driver: orm

    mappings:
        topic_image:
            uri_prefix: /img/topic
            upload_destination: '%kernel.project_dir%/public/img/topic'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        category_image:
            uri_prefix: /img/category
            upload_destination: '%kernel.project_dir%/public/img/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        forum_image:
            uri_prefix: /img/forum
            upload_destination: '%kernel.project_dir%/public/img/forum'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
